swagger: "2.0"
info:
  version: "1.0.0"
  title: optee
  description: the best website ever it'll help you with your life
  contact:
    name: Support
    email: lesley.yc@gmail.com
host: localhost:3000
consumes:
  - application/json
produces:
  - application/json
paths:
  $ref: "./paths/index.yaml"
definitions:
  $ref: "./definitions/index.yaml"
