message:
  name: message
  in: object
  description: message string that you pass in when you render the error page
  required: false
  schema:
    type: string
theme:
  name: theme
  in: object
  description: theme
  required: false
  schema:
    type: string
quote:
  name: quote
  in: object
  description: quote on auth page
  required: true
  schema:
    type: string
problem_tasks:
  name: problem tasks
  in: object
  description: problem tasks
  required: true
  schema:
    type: array
