const { see, hourglass } = require("code_clarity")
see.is("i want to make him very happy")
hourglass.start("thinking about the purpose of my life")
see.problem("need to sleep or take a break")
see.should("do some easy tasks right now, like testing for effective_knex")

see.story("i will be able to find what it means to love, and will be more considerate, perfect, joyful and more Christ like as a result")
see.problem("how do we become perfect?")
see.should("we should always strive to be perfect")
see.is("we forget what we want")
see.hypothesis("omg drugs are great. they really help you relax. it really is like the Queen's Gambit")
see.step("learn how to be more chill")
see.step("identify attributes of others that are chill")
see.step("be better at talking and telling stories")
see.step("follow what your passion is")
see.step("be the best at your passion, this is such a cool tool, lezz.")
see.step("calm down enough to channel your love, energy and passion into art")
see.step("reach your own expectations, reach and maintain 110")
see.step("look back to what you wanted to do, didn't you make out quizlet cards for it, how do we create electronic tools that are helpful for your own life?")
see.step("identify what is most valuable to you, and create tools that help you get to that level, it is, really quite similar to self-actualization. how do we become the absolute best?")
see.step("spend more time coding, but also track your start and end times, learn what is most effective and efficient for you.")
see.problem("before deciding to do something, identify what the problem is, and see if there is a quicker way to resolve or fix something, to understand other people, ultimately, is to understand ourselves.")
see.problem("we rarely understand our significant others")
see.story("users will be able to better understand their significant others")
see.story("the developer will be able to maximize investment so as to reinvest in the company as well as ensure that she creates a life that her parents will be proud of")
see.should("we should go into financial industries if we want money")
see.is("we can think more about what softwares are available as a service, and then aim to create tools that will help us easily maintain that service")
see.step("identify tools that people pay for in order to use a specific service")